baseURL = "/"
title   = "Namaste Programming"

DefaultContentLanguage = "en"
theme = "hello-friend-ng"

pygmentsCodefences = false
pygmentsUseClasses = false

rssLimit  = 100  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = "notes-ravindrasecureserver-online"

buildDrafts  = false
buildFuture  = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = false
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Namaste Programming"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "category"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Namaste Programming YouTube"
  keywords = "homepage, blog, science, informatics, development, programming, freelancer, selbstständig, projects, cloud, software"
  images = [""]

  homeSubtitle = "YouTube Channel"

  disableReadOtherPosts = false

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/rhazdon/homepage/commit/"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [params.logo]
    logoText     = "$cd Namaste Programming"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/NamasteProgramm "

  [[params.social]]
    name = "email"
    url  = "mailto:namasteprogramming@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/NamasteProgramming/"

  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/c/NamasteProgramming"
   

[languages]
  [languages.en]
    subtitle  = "Notes"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Videos"
    url        = "videos/"
